version: "3.9"

volumes:
  postgres_data:

services:
  olympics_db:
    image: postgres:14.5

    environment:
      POSTGRES_DB: sidorenkov_204
      POSTGRES_USER: sidorenkov_204
      POSTGRES_PASSWORD: sidorenkov_204
      PGDATA: /var/lib/postgresql/data/pgdata-olympics

    volumes:
      - ./docker/db/scripts/olympics.sql:/docker-entrypoint-initdb.d/olympics.sql
      - ./dz:/var/lib/postgresql/data

    ports:
      - "5432:5432"
